// capture.js — snapshot the LIVE editor's frames as test fixtures, REDACTED.
//
// WHY THIS EXISTS. Every fixture in this suite before 2026-09-09 was hand-written from the code's own
// model of the world, so where that model was wrong the tests agreed with it: the suite went 349 ->
// 376 passing across one night in which the live system misrouted six different ways. A fixture has
// to come from reality to contradict the code.
//
// WHAT IS KEPT: the tokens classification actually reads — `LOOMROLE=` sign-off lines, `worktrees/<role>`
// and `loom|Containers/<repo>/` paths, the model footer, the limit banner, the busy chip — at their real
// positions, with real repetition counts, so purity ratios and tail contents are preserved exactly.
// WHAT IS DROPPED: every other word of the user's conversation, replaced by filler of the same length so
// frame sizes (which decide ties) survive. Nothing readable about the work is stored.
//
//   ELECTRON_RUN_AS_NODE=1 codium test/fixtures/capture.js <outdir>
//
// Re-run it when the world changes; commit what it writes, and update manifest.json's `truth` by HAND
// from what you measured — the manifest is the ground truth the code is judged against, so it must not
// be generated by the same code under test.
const path = require("path");
const fs = require("fs");
const OUT = path.join(__dirname, "..", "..", "out");
const { readFrames } = require(path.join(OUT, "cdp.js"));
const { busRepos } = require(path.join(OUT, "registry.js"));

const KEEP = [
  /^[\s>*`|\-]*LOOMROLE[\s=:]+[a-z][a-z0-9\-]*\s*$/gim,        // sign-off lines
  // Trailing slash OPTIONAL: `worktrees/developer` at the end of a sentence is the same evidence as
  // `worktrees/developer/a.ts`, and requiring the slash erased it — the capture self-check caught
  // exactly that on frame a57ba8a7, which classified `developer` live and null as a fixture.
  /(?:loom|Containers|worktrees)[\/\\][A-Za-z0-9_.\-]+[\/\\]?/g,
  /\b(?:Opus 5|Sonnet 5|Haiku 4\.5|Fable 5\.1)\b/g,             // model footer names
  /\b(?:Medium|High|Low)\b/g,
  /Bypass permissions|Remote Control/g,
  /You[''´]?ve hit your [^\n·]+/g,                              // limit banners
  /Usage limit reached\s*·\s*[^\n·]+/g,
  /resets\s+(?:in\s+)?(?:\d+\s*[mhd]|soon|\d{1,2}(?::\d{2})?\s*[ap]m[^\n)]*\)?)/gi,
  /Claude is working|esc to interrupt|Stop responding/g,        // busy chip
  /\/model [a-z0-9\-.\[\]]+/g,                                  // injected commands, to count them
  /\[loom-(?:notify|stall|resume|restart)\][^\n]{0,80}/g,
  /Set model to/g,
];

/** Replace everything except the KEEP tokens with same-length filler. */
function redact(text) {
  const keep = [];
  for (const re of KEEP) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m[0].length) keep.push([m.index, m.index + m[0].length]);
      if (!re.global) break;
    }
  }
  keep.sort((a, b) => a[0] - b[0]);
  const merged = [];
  for (const [s, e] of keep) {
    const last = merged[merged.length - 1];
    if (last && s <= last[1]) last[1] = Math.max(last[1], e);
    else merged.push([s, e]);
  }
  const out = [];
  let at = 0;
  for (const [s, e] of merged) {
    if (s > at) out.push(filler(text.slice(at, s)));
    out.push(text.slice(s, e));
    at = e;
  }
  if (at < text.length) out.push(filler(text.slice(at)));
  return out.join("");
}
/** Same length, same newline structure (line counts matter for line-anchored regexes), no content.
 *  STRUCTURAL SEPARATORS SURVIVE: the model footer is matched as `<model> · <effort> · <chip>`, so
 *  filling the `·` between kept tokens silently destroyed it — measured on the first capture, frame
 *  849774ff read model=null as a fixture and "Fable 5.1" live. Anything a regex uses to JOIN two kept
 *  tokens is structure, not content. */
function filler(s) {
  return s.replace(/[^\n·|]/g, (c) => (/\s/.test(c) ? " " : "x"));
}

// ── fidelity: a redacted fixture is only worth having if it BEHAVES like the frame it came from ──
// Checked against the SAME text in the SAME instant — the live panels grow between reads, so a
// second dump is a different frame and any comparison against it measures the clock, not the redaction.
const { classify, attributeRepo, detectOwner } = require(path.join(OUT, "roles.js"));
const { boardRoles } = require(path.join(OUT, "registry.js"));
const { detectModel } = require(path.join(OUT, "models.js"));
const { detectLimit } = require(path.join(OUT, "limits.js"));
const { isBusy } = require(path.join(OUT, "sessions.js"));

function behaviour(text, repos) {
  const repo = attributeRepo(text, repos).repo;
  const c = repo ? classify(text, new Set(boardRoles(repo)), repo) : { role: null, purity: 0, source: null };
  const m = detectModel(text), l = detectLimit(text, 0);
  return {
    repo, role: c.role, source: c.source, owner: detectOwner(text), busy: isBusy(text),
    model: m ? m.model : null, effort: m ? m.effort : null,
    limited: l ? l.limited : false, kind: l ? l.kind : null, len: text.length,
  };
}

(async () => {
  const dir = process.argv[2] || path.join(__dirname, "live");
  fs.mkdirSync(dir, { recursive: true });
  const repos = busRepos();
  const frames = (await readFrames()).filter((f) => f.webviewId && (f.text || "").length > 2000);
  // THE BUS IS PART OF THE INPUT. Classification reads each project's roster and its naming aliases,
  // and the tests run with HOME forced to a sandbox, so a fixture that is only frames describes half
  // a world: `boardRoles()` comes back empty and every frame classifies as null. Snapshot the roster,
  // the aliases and the board-declared orchestrator frames alongside the panels.
  const { roleAliases, ownerRoleFor } = require(path.join(OUT, "naming.js"));
  const { boardOwnerFrames, busDeclaredFrames } = require(path.join(OUT, "registry.js"));
  const bus = {};
  for (const r of repos) {
    bus[r] = {
      roles: boardRoles(r),
      aliases: Object.fromEntries(roleAliases(r)),
      ownerRole: ownerRoleFor(r),
      ownerFrames: [...boardOwnerFrames(r)],
      // The `<role>.id` files, which the buses use to address frames and which this extension did not
      // read until 2026-09-09. Capturing only what the code already understood is how the previous
      // fixture set encoded its blind spot: ReciEats' orchestrator was invisible AND unfixturable.
      declared: busDeclaredFrames(r),
      // Written by the session itself, so it is the evidence for which bus owns a contested frame.
      mailboxWritten: Object.fromEntries(boardRoles(r).map((role) => {
        try { return [role, fs.statSync(path.join(require("os").homedir(), ".claude", "loom", r, role, "status.json")).mtimeMs]; }
        catch { return [role, null]; }
      })),
    };
  }
  const manifest = { capturedAt: new Date().toISOString(), buses: repos, bus, frames: [] };
  let rejected = 0;
  for (const f of frames) {
    const id = f.webviewId.slice(0, 8);
    const red = redact(f.text);
    const before = behaviour(f.text, repos), after = behaviour(red, repos);
    const diff = Object.keys(before).filter((k) => JSON.stringify(before[k]) !== JSON.stringify(after[k]));
    if (diff.length) {
      rejected++;
      console.error(`REJECTED ${id}: redaction changed ${diff.join(", ")}`);
      for (const k of diff) console.error(`    ${k}: live ${JSON.stringify(before[k])} -> fixture ${JSON.stringify(after[k])}`);
      continue;                                  // never commit a fixture that lies
    }
    fs.writeFileSync(path.join(dir, `${id}.txt`), red);
    manifest.frames.push({
      id, webviewId: f.webviewId, contextPct: f.contextPct ?? null,
      // MEASURED from the live frame, not asserted by hand — and identical in the fixture, which is
      // what the check above proves. The test asserts the TRACKER's per-window decisions on top.
      measured: before,
    });
  }
  fs.writeFileSync(path.join(dir, "manifest.json"), JSON.stringify(manifest, null, 2));
  console.log(`captured ${manifest.frames.length} frame(s)${rejected ? `, REJECTED ${rejected}` : ""} -> ${dir}`);
})();
